import EmitterWithLogging from "../../helpers/emitter-with-logging";

const EVENT_NAMES = {
  ACTION_START: "ACTION_START",
  ACTION_CANCEL: "ACTION_CANCEL",
  ACTION_COMPLETE: "ACTION_COMPLETE",
  PLAYER_CARD_SELECT: "PLAYER_CARD_SELECT",
  PLAYER_CARD_DESELECT: "PLAYER_CARD_DESELECT",
  PLAYER_CARD_FOCUS: "PLAYER_CARD_FOCUS",
  PLAYER_CARD_DEFOCUS: "PLAYER_CARD_DEFOCUS",
  PLAYER_CARD_DISCARD: "PLAYER_CARD_DISCARD",
  END_PLAYER_TURN: "END_PLAYER_TURN"
};

const emitter = new EmitterWithLogging(`Player Manager`);

export { emitter, EVENT_NAMES };
